[package]
name = "streebog"
version = "0.8.0"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Streebog (GOST R 34.11-2012) hash function"
documentation = "https://docs.rs/streebog"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "streebog", "gost", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx" }
byte-tools = { git = "https://github.com/mesalock-linux/rustcrypto-utils-sgx" }
block-buffer = { git = "https://github.com/mesalock-linux/rustcrypto-utils-sgx" }
opaque-debug = "0.2"
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[dev-dependencies]
#digest = { version = "0.8", features = ["dev"] }
#hex-literal = "0.1"

[features]
default = ["std", "mesalock_sgx"]
std = ["digest/std", "mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
